"""Add Address Table

Revision ID: 0904da817363
Revises: 
Create Date: 2017-09-28 03:20:40.625588

"""
from alembic import op
import sqlalchemy as sa
import sideboard.lib.sa

# revision identifiers, used by Alembic.
revision = '0904da817363'
down_revision = None
branch_labels = ('darecms',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sideboard.lib.sa.UUID(), nullable=False),
    sa.Column('user_id', sideboard.lib.sa.UUID(), nullable=False),
    sa.Column('street', sa.Unicode(), server_default='', nullable=False),
    sa.Column('street_two', sa.Unicode(), nullable=True),
    sa.Column('city', sa.Unicode(), server_default='', nullable=False),
    sa.Column('state', sa.Unicode(), server_default='', nullable=False),
    sa.Column('zip_code', sa.Unicode(), server_default='', nullable=False),
    sa.Column('country', sa.Unicode(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
