"""Add priority to address model

Revision ID: fd805a79d25e
Revises: f131f027acfe
Create Date: 2017-09-28 22:41:42.034722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd805a79d25e'
down_revision = 'f131f027acfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'priority')
    # ### end Alembic commands ###
